2025-08-22 18:40:26,251 INFO: GitLab Analytics Hub startup [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:32]
2025-08-22 18:40:26,252 INFO: --- PATH DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:35]
2025-08-22 18:40:26,252 INFO: App Root Path: D:\Documents\Code\gitlab-automation-suite\app [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:36]
2025-08-22 18:40:26,253 INFO: App Template Folder: templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:37]
2025-08-22 18:40:26,253 INFO: Full Template Path: D:\Documents\Code\gitlab-automation-suite\app\templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:38]
2025-08-22 18:40:26,254 INFO: --- END PATH DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:39]
2025-08-22 18:40:27,258 INFO: --- BLUEPRINT DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:46]
2025-08-22 18:40:27,259 INFO: Registered Blueprint: 'main' [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:48]
2025-08-22 18:40:27,260 INFO:   - Blueprint Template Folder: ../templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:49]
2025-08-22 18:40:27,261 INFO: --- END BLUEPRINT DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:50]
2025-08-22 18:40:54,692 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-22 18:40:54,693 INFO: Generating Triage to Milestone Lag Report based on issue activity. [in D:\Documents\Code\gitlab-automation-suite\app\main\logic.py:367]
2025-08-22 18:41:07,786 INFO: Fetched ALL 720 issues with filters: {'updated_after': '2025-08-01', 'updated_before': '2025-08-22', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:299]
2025-08-22 18:43:22,245 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-22 18:43:22,245 INFO: Generating Triage to Milestone Lag Report based on issue activity. [in D:\Documents\Code\gitlab-automation-suite\app\main\logic.py:367]
2025-08-22 18:43:34,170 INFO: Fetched ALL 720 issues with filters: {'updated_after': '2025-08-01', 'updated_before': '2025-08-22', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:299]
2025-08-22 18:44:46,138 ERROR: Error fetching milestone events for issue 1588/182: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:66]
2025-08-22 18:45:06,167 ERROR: Error fetching milestone events for issue 67/21847: HTTPSConnectionPool(host='emu.hinagro.com', port=443): Max retries exceeded with url: /api/v4/projects/67/issues/21847/resource_milestone_events (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B80F4EF4D0>, 'Connection to emu.hinagro.com timed out. (connect timeout=20)')) [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:66]
2025-08-22 18:45:48,884 ERROR: Error fetching milestone events for issue 1588/180: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:66]
2025-08-22 18:46:13,400 ERROR: Error fetching milestone events for issue 1588/179: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:66]
2025-08-22 18:46:52,897 ERROR: Error fetching milestone events for issue 2327/17: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:66]
